### ISSUE TITLE
casting null values to any datatype raise exception

### ISSUE THREAD

**Issue by kattunga** [ahausladen/JsonDataObjects#14]
now if we try to cast a null value to any type of data an exception is raised:

```pascal
var
  doc: TJsonObject;
  v: variant;
begin
  doc := TJsonObject.Create;
  try
    doc['nullvalue'] := null;

    // any of this raise an exception
    v := doc['nullvalue'].Value;
    v := doc['nullvalue'].IntValue;
    v := doc['nullvalue'].LongValue;
    v := doc['nullvalue'].FloatValue;
    v := doc['nullvalue'].DateTimeValue;
    v := doc['nullvalue'].BoolValue;

  finally
    doc.Free;
  end;
end;
```
Why don't we cast nulls like if it is jdtNone?

Also DataSet fields cast nulls to required datatypes:
```pascal
  // if DataField.IsNull
  v := DataField.AsString;  // this return empty string
  v := DataField.AsInteger;  // this return 0
  ...
```
Also VarToString function:
```pascal
  v := VarToString(null);   // this return empty string
```

I would like to implement this but I like to ask you first.

Regards
Christian

**Comment by ahausladen** [comment]
Null means "JavaScript null". And that means that it is an object. And JsonDataObject doesn't allow to cast an object to a value type.

**Comment by ahausladen** [comment]
You can now control this by setting "JsonSerializationConfig.NullConvertsToValueTypes" to "True". The default is "False".
