### ISSUE TITLE
Trying to build for a 64-bit target, I get several errors

### ISSUE THREAD

**Issue by jkaster** [ahausladen/JsonDataObjects#17]
[DCC Error] JsonDataObjects.pas(2004): E2089 Invalid typecast
[DCC Error] JsonDataObjects.pas(2009): E2089 Invalid typecast
[DCC Error] JsonDataObjects.pas(2052): E2089 Invalid typecast
[DCC Error] JsonDataObjects.pas(6793): E2037 Declaration of 'Realloc' differs from previous declaration
[DCC Error] JsonDataObjects.pas(6797): E2003 Undeclared identifier: 'Capacity'
[DCC Error] JsonDataObjects.pas(6800): E2003 Undeclared identifier: 'FBytes'
[DCC Error] JsonDataObjects.pas(6803): E2008 Incompatible types
[DCC Error] JsonDataObjects.pas(6816): E2008 Incompatible types
[DCC Error] JsonDataObjects.pas(899): E2065 Unsatisfied forward or external declaration: 'TJsonBytesStream.Realloc'

Does the code currently only work for 32-bit targets? (I was compiling it for iOS)

**Comment by ahausladen** [comment]
64 bit Windows is no problem. But 64 bit mobile compilers are because EMBT thought that it would be a  great idea to make LongWord 32 bit under Win32, Win64, ARM32 but 64 bit under ARM64.
