### ISSUE TITLE
How to get each item(it's Object) from the ARRAY?

### ISSUE THREAD

**Issue by chonghai** [ahausladen/JsonDataObjects#20]
How to get each item(Object, not a single Value) from the ARRAY?
thks!

**Comment by chonghai** [comment]
just like this question:
http://stackoverflow.com/questions/33127718/how-can-i-access-a-sub-object-in-jsondataobjects

**Comment by ahausladen** [comment]
You can use the Path[] property.

```Delphi
procedure Test(AData: TJsonObject);
begin
  Obj := MyData.Path['MyArray[1].MySubObject'];
  ...
end;
```

**Comment by chonghai** [comment]
thks for your answer.
but I test it , it seems not work.
I give a JSON string:

{"menu": {
    "header": "SVG Viewer",
    "items": [
        {"id": "Open"},
        {"id": "OpenNew", "label": "Open New"},
        null,
        {"id": "Help"},
        {"id": "About", "label": "About Adobe CVG Viewer..."}
    ]
}}

How can I Get "Help" in  {"id": "Help"}?
 Thks!

**Comment by ahausladen** [comment]
```Delphi
if Json.Path['menu.items[3].id'] <> 'Help' then
  raise Exception.Create('Something is wrong');
```

**Comment by chonghai** [comment]
sorry, I make mistake, I user a wrong JSON string.
Your code is good.

another question:
How to use iterate through the array to show each "id"?
like:
```delphi
for jsonitem in obj['menu'].['items'] do
  showMessage(jsonitem['id']);
```

**Comment by ahausladen** [comment]
"for in" is not supported. You have to iterate manually using the array's Count property.

**Comment by chonghai** [comment]
OK, thanks a lot of!
