### ISSUE TITLE
Provide support for EncodeBase64 / DecodeBase64

### ISSUE THREAD

**Issue by TrueWodzu** [ahausladen/JsonDataObjects#22]
Sometimes values are encoded in Base64. After parsing file there is a need to decode such value. It would be nice if JsonDataObjects library provided function to decode the value.

**Comment by ronaldhoek** [comment]
In Delphi 2009/2010/XE there is unit EncdDecd.pas (Soap.EncdDecd.pas for Delphi XE2) containing the functions EncodeBase64 and DecodeBase64.

**Comment by TrueWodzu** [comment]
Thanks for the info, I knew that there are many implementation of these functions altough I didn't know that Delphi itself has one.
