### ISSUE TITLE
Difference among other implementations

### ISSUE THREAD

**Issue by geskill** [ahausladen/JsonDataObjects#23]
Right now, there are several JSON implementations available. Whats the difference of this among others? Is it speed, scalability or a low footprint?

- JSON delphi library [uLkJSON.pas](http://sourceforge.net/projects/lkjson/)
- Integrated [System.Json](http://docwiki.embarcadero.com/Libraries/Seattle/en/System.JSON)
- ISuperObject implementations [hgourvest/superobject](https://github.com/hgourvest/superobject) or [onryldz/x-superobject](https://github.com/onryldz/x-superobject)

**Comment by ahausladen** [comment]
From the readme.md:


Features
--------
* Fast dual JSON parser for parsing UTF8 and UTF16 without conversion
* Automatic creation of arrays and objects
* Easy access mode with implicit operators
* Compact and formatted output modes
* Variants support
* Null can be auto-typecasted to a value type if JsonSerializationConfig.NullConvertsToValueTypes is set to True
* Win32, Win64 and ARM Android support (MacOS and iOS may work)
