### ISSUE TITLE
Variable requiered errors

### ISSUE THREAD

**Issue by Geont** [ahausladen/JsonDataObjects#3]
When trying to use JsonDataObjects we found that on one of ours computers it gives in XE7 (without Update 1) three E2036 Variable required errors. These are on lines 1965, 3755, 3760. This happens only on this one computer (not reproducible on others (XE7 Update 1 installed)) but we are unsure what causes this.

**Comment by ahausladen** [comment]
I can't fix XE7 compiler bugs. Looks like XE7 Update 1 got rid of the bug.
