### ISSUE TITLE
UTF8 Error

### ISSUE THREAD

**Issue by lynch1983** [ahausladen/JsonDataObjects#33]
When I use JsonDataObjects,pas (in Delphi XE) like this:

procedure doParseUTF8();
var
  aJson: TJsonObject;
  aJsonStr: string;
  aUTF8Str: UTF8String;
begin
  aJsonStr := '{"123":{"abc":{"efg":"hij"}}}';
  aUTF8Str := UTF8Encode(aJsonStr);

  aJson := TJsonObject.Create;
  try
    aJson.FromUtf8JSON(aUTF8Str);
    ShowMessage(aJson.ToJSON);
  finally
    aJson.Free;
  end;
end;

I get message '{"12":{"ab":{"ef":"hi"}}}'.
The Key and The Value all have been cut.

this Error also in parse from UTF8 file.

**Comment by ahausladen** [comment]
I can't reproduce this behavior if I run your code (neither in XE nor in 10.1). Did you use the newest source code?

**Comment by lynch1983** [comment]
[JsonUTF8.zip](https://github.com/ahausladen/JsonDataObjects/files/552192/JsonUTF8.zip)

**Comment by ahausladen** [comment]
Do you have XE Update 1 installed? I have and I don't see that bug with your test application. The only thing that could be different is Utf8ToUnicode.

**Comment by lynch1983** [comment]
I run it in XE( with Update 1 ), the demo run OK.
I'm sorry to bother you.
