### ISSUE TITLE
Loading bool values

### ISSUE THREAD

**Issue by NilsHoyer** [ahausladen/JsonDataObjects#37]
Hi Andreas,

I suggest to change this line:
https://github.com/ahausladen/JsonDataObjects/blob/master/Source/JsonDataObjects.pas#L2571

From:
```Delphi
Result := string(FValue.S) = 'true';
```
to:
```Delphi
Result := BoolToStr(string(FValue.S));
```

... this would allow to use "True" or "TRUE" also inside the JSON file...

**Comment by brunosanson** [comment]
👍

**Comment by ahausladen** [comment]
"True" and "TRUE" are no valid JSON expressions.
See http://www.json.org/

**Comment by NilsHoyer** [comment]
Thank you for your explaination.
