### ISSUE TITLE
Can't parse mixed types in an array 

### ISSUE THREAD

**Issue by thachngopl** [ahausladen/JsonDataObjects#39]
Hi,
The JsonDataObjects can't parse this json string:
```
[1,2,3,\"This is a test\",{\"a\":\"a\"}]
```

You can get that json string by executing this code in Firefox or Chrome:
```javascript
JSON.stringify([1, 2, 3, "This is a test", {"a": "a"}]);
```

**Comment by ahausladen** [comment]
That's **no valid** JSON. That's how a C based programming language needs the string in the code editor. The string that is returned by JSON.stringify() doesn't contain the escape characters. If you use console.log() to output the string to the console you see that there are no escape characters.
Furthermore the length of the returned string is 34 and not 40.

```javascript
console.log(JSON.stringify([1, 2, 3, "This is a test", {"a": "a"}]));
console.log(JSON.stringify([1, 2, 3, "This is a test", {"a": "a"}]).length);
```
outputs:
```javascript
[1,2,3,"This is a test",{"a":"a"}]
34
```
