### ISSUE TITLE
Should line not use 'JsonMemInfoMainBlockStart' instead of 'JsonMemInfoBlockStart'

### ISSUE THREAD

**Issue by ronaldhoek** [ahausladen/JsonDataObjects#56]
Accidentally stumbled upon this:

https://github.com/ahausladen/JsonDataObjects/blob/72a25adc508387a2797980b5ed963e00f6d1ebc0/Source/JsonDataObjects.pas#L1156

Should that line not use `JsonMemInfoMainBlockStart` instead of `JsonMemInfoBlockStart`?

**Comment by ronaldhoek** [comment]
Thanks, but the currently referenced 'fix' points to different commit (which does not show the fix).

It should be: https://github.com/ahausladen/JsonDataObjects/commit/2ddcef634c0a4c070c2cda55d060b7287d029a47

**Comment by ahausladen** [comment]
Somehow I committed two "Fixed #56". I never intended to commit the *.dproj file changes. I can't fix this without rewriting the history what will break the git repository for others.

**Comment by ronaldhoek** [comment]
No problem, it's now referenced using my comment ;)
