### ISSUE TITLE
Clone object with problem on Delphi XE

### ISSUE THREAD

**Issue by marcosdemelo** [ahausladen/JsonDataObjects#6]
When I clone '{ "foo": [ "bar", {}, null, true, false, { "keaa": "value" } ] }', my result at "ClonedObj.ToJSON(True)" is '{"fo":["ba",{},null,true,false,{"ke":"valu"}]}'.

Analyzing, can you see that keys are resulting without the last char.

I'm using the example shown in the Readme .

**Comment by ahausladen** [comment]
I can't reproduce this.

**Comment by marcosdemelo** [comment]
I'll find a time and inspect my problem, if I find the problem will report here.
