### ISSUE TITLE
Case insensitive names to access nodes

### ISSUE THREAD

**Issue by jairgza** [ahausladen/JsonDataObjects#63]
Hi,  please consider add some option to access/find nodes in a case insensitive way.

Some times if the name is not case equal, I get an empty string

```
jo['NAME'] := 'my name';

s := jo.S['Name'];
s is empty

```
I know its a logic error and the names must match but, since jsonDataObject returns an empty default value if no node exists without error or warning, looking for nodes in a case insensitive way can reduce this kind of issues that sometimes are difficult to track.

cheers

**Comment by cesco69** [comment]
According to [JSON-RPC spec][1], JSON is Case-Sensitive.

> 9.0 Case-Sensitivity of Procedure and Parameter Names
> 
> Conforming implementations MUST treat
> procedure and parameter names as being
> case-sensitive such the names bar and
> BAR would be seen as two distinct
> entities.

  [1]: http://jsonrpc.org/historical/json-rpc-1-1-alt.html#service-procedure-and-parameter-names
