### ISSUE TITLE
functions to get values to variants and to add variant values

### ISSUE THREAD

**Issue by kattunga** [ahausladen/JsonDataObjects#8]
Hi, actually you can't do the following:
```
var
  v: variant;
begin
  v := jsonobject['my name']; 
end;
```
It would be nice to have a new property like:
```
v := jsonobject.V['my name'];
```
To return value to a variant with the datatype stored in json datavalue. Of course this should raise an exception if you are trying to cast an object or an array.

It would be useful to to have an overload of TObjectArray.Add procedure to add a variant value to an array using the vartype of the value to determine json datatype.

Actually I do this with 2 procedures, I don't want to change your source code because later is a madness to maintain updates.

With best regards
Christian

**Comment by ahausladen** [comment]
You can fork, make changes, commit and push them to your fork and then create a pull request. That way you have your changes and if I find them useful I can pull them and integrate them into my branch.

**Comment by kattunga** [comment]
I'll do that. Thank you.
